/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.pap1.presentacion;

import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author martin
 */
public class AgregarDonacion extends JInternalFrame {

    /**
     * Creates new form AgregarDonacion
     */
    public AgregarDonacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        RadioAlimento = new javax.swing.JRadioButton();
        RadioArticulo = new javax.swing.JRadioButton();
        ButtonAceptar = new javax.swing.JButton();
        ButtonCancelar = new javax.swing.JButton();
        Dia = new javax.swing.JSpinner();
        Mes = new javax.swing.JSpinner();
        Ano = new javax.swing.JSpinner();

        jLabel1.setText("Agregar Donacion");

        jLabel2.setText("Fecha Ingresada:");

        jLabel3.setText("Tipo:");

        buttonGroup1.add(RadioAlimento);
        RadioAlimento.setText("Alimento");
        RadioAlimento.setToolTipText("");
        RadioAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioAlimentoActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioArticulo);
        RadioArticulo.setText("Articulo");

        ButtonAceptar.setText("Aceptar");
        ButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAceptarActionPerformed(evt);
            }
        });

        ButtonCancelar.setText("Cancelar");
        ButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarActionPerformed(evt);
            }
        });

        Dia.setPreferredSize(new java.awt.Dimension(48, 23));

        Mes.setPreferredSize(new java.awt.Dimension(48, 23));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Ano, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel3)
                        .addGap(28, 28, 28)
                        .addComponent(RadioAlimento)
                        .addGap(40, 40, 40)
                        .addComponent(RadioArticulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(ButtonAceptar)
                        .addGap(59, 59, 59)
                        .addComponent(ButtonCancelar)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(RadioAlimento)
                    .addComponent(RadioArticulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAceptar)
                    .addComponent(ButtonCancelar))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAceptarActionPerformed
        String mensaje = "Algo salio mal";
        try {
            int dia = (Integer)(Dia.getValue());
            int mes = (Integer)(Mes.getValue());
            int ano = (Integer)(Ano.getValue());

            System.out.println("Fecha ingresada: " + dia + "/" + mes + "/" + ano);

            if(dia < 1 || dia > 31){
                mensaje = "Día inválido";
                throw new Exception();
            }
            if(mes < 1 || mes > 12){
                mensaje = "Mes inválido";
                throw new Exception();
            }

            if(ano <1900 || ano >2024){
                mensaje = "Ano invalido";
                throw new Exception();
            }

            if((mes == 4 || mes == 6 || mes == 9 || mes == 11) && dia > 30){
                mensaje = "Día inválido";
                throw new Exception();
            }

            if(mes == 2) {
                if(dia > 29) {
                    mensaje = "Día inválido";
                    throw new Exception();
                }
                if(dia == 29 && !(ano % 4 == 0 && (ano % 100 != 0 || ano % 400 == 0))) {
                    mensaje = "Día inválido en año no bisiesto";
                    throw new Exception();
                }
            }
            
            if(!RadioAlimento.isSelected() && !RadioArticulo.isSelected()){
                mensaje = "Seleccione un tipo de donacion";
                throw new Exception();
            }
            
            if(RadioAlimento.isSelected()){
                var panel = new AgregarAlimento(this);
                panel.setVisible(true);

                JDesktopPane desktopPane = getDesktopPane();
                if (desktopPane != null) {
                    desktopPane.add(panel);
                    panel.setSelected(true);
                    panel.setVisible(true);
                }
            }
            else {
                var panel = new AgregarArticulo(this);
                panel.setVisible(true);

                JDesktopPane desktopPane = getDesktopPane();
                if (desktopPane != null) {
                    desktopPane.add(panel);
                    panel.setSelected(true);
                    panel.setVisible(true);
                }
            }
            
        }
        catch (Exception e) {
        JOptionPane.showMessageDialog(null, 
        mensaje, 
        "Error", 
        JOptionPane.ERROR_MESSAGE);
        }   
    }//GEN-LAST:event_ButtonAceptarActionPerformed

    private void RadioAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioAlimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioAlimentoActionPerformed

    private void ButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_ButtonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Ano;
    private javax.swing.JButton ButtonAceptar;
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JSpinner Dia;
    private javax.swing.JSpinner Mes;
    private javax.swing.JRadioButton RadioAlimento;
    private javax.swing.JRadioButton RadioArticulo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
