/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.pap1.presentacion;


import com.mycompany.pap1.interfaces.IControladorDonacion;
import com.mycompany.pap1.logica.ControladorDonacion;
import java.awt.BorderLayout;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author martin
 */
public class FramePrincipal extends javax.swing.JFrame {
    
    private JDesktopPane desktopPane;


    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
        initCustomComponents();
    }
        private void initCustomComponents() {
        // Inicializar el JDesktopPane
        desktopPane = new JDesktopPane();
        setContentPane(desktopPane);
        desktopPane.setLayout(new BorderLayout());
        
        jMenuItem9.addActionListener(e -> mostrarModificarDonacion());
        jMenuItem2.addActionListener(e -> mostrarAgregarDonacion());
        jMenuItem1.addActionListener(e -> mostrarAgregarUsuario());
        jMenuItem4.addActionListener(e -> mostrarListarBeneficiarios());
        jMenuItem7.addActionListener(e -> mostrarListarDistribucionesEstado());
        jMenuItem10.addActionListener(e -> mostrarModificarDistribucion());

        IControladorDonacion controlador = new ControladorDonacion();

    }
    private void mostrarAgregarUsuario() {
        AgregarUsuario agregarUsuarioFrame = new AgregarUsuario();
        desktopPane.add(agregarUsuarioFrame);
        agregarUsuarioFrame.setVisible(true);
    }
    private void mostrarAgregarDonacion() {
    IControladorDonacion controlador = new ControladorDonacion();
    AgregarDonacion agregarDonacionFrame = new AgregarDonacion(controlador);
    desktopPane.add(agregarDonacionFrame);
    agregarDonacionFrame.setVisible(true);
    }

    private void mostrarModificarDonacion() {
        IControladorDonacion controlador = new ControladorDonacion();
        ModificarDonacion modificarDonacionFrame = new ModificarDonacion(controlador);
        desktopPane.add(modificarDonacionFrame);
        modificarDonacionFrame.setVisible(true);
    }
    
    private void mostrarListarBeneficiarios() {
        var panel = new ListarBeneficiarios();
        desktopPane.add(panel);
        panel.setVisible(true);
    }
    
    private void mostrarListarDistribucionesEstado() {
        var panel = new ListarDistribucionesEstado();
        desktopPane.add(panel);
        panel.setVisible(true);
    }
    
    private void mostrarModificarDistribucion() {
        var panel = new ModificarDistribucion();
        desktopPane.add(panel);
        panel.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenido");

        jMenu1.setText("Inicio");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ingreso");

        jMenuItem1.setText("Usuario");
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Donacion");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Distribucion");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Modificar");

        jMenuItem8.setText("Usuario");
        jMenu4.add(jMenuItem8);

        jMenuItem9.setText("Donacion");
        jMenu4.add(jMenuItem9);

        jMenuItem10.setText("Distribucion");
        jMenu4.add(jMenuItem10);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Consultas");

        jMenuItem4.setText("Beneficiarios");
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Beneficiarios Por Zona");
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("Beneficiarios Por Estado");
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("Distribuciones Por Estado");
        jMenu3.add(jMenuItem7);

        jMenuItem11.setText("Distribuciones Por Zona");
        jMenu3.add(jMenuItem11);

        jMenuItem12.setText("Reporte de Zonas");
        jMenu3.add(jMenuItem12);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel1)
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(236, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
