/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pap1.presentacion;

import com.mycompany.pap1.datatypes.dtDistribucion;
import com.mycompany.pap1.fabricas.FabricaCDistribucion;
import com.mycompany.pap1.logica.EstadoDistribucion;
import java.time.LocalDate;
import java.time.Month;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author martin
 */
public class ModificarDistribucion extends JInternalFrame {

    /**
     * Creates new form ModificarDistribucion
     */
    
    List<dtDistribucion> distribuciones;
    
    public ModificarDistribucion() {
        initComponents();
        
        ComboBoxDistribucion.removeAllItems();
        
        distribuciones = FabricaCDistribucion.getControlador().getTodasDistribuciones();
        
        String[] distri = new String[distribuciones.size() +2];
        
        distri[0] = "<>";
        int index = 1;
        
        for (var d : distribuciones) {
            String g = d.getFechaEntrega().toString() + " " + d.getEstadoDistribucion().toString() + " " + d.getFechaPreparacion().toString();
            ComboBoxDistribucion.addItem(g);
        }
       
        for (var d : distri) {
            ComboBoxDistribucion.addItem(d);
        }
        
        String[] estados = {"PENDIENTE","EN CAMINO","ENTREGADO"};
        
        ComboBoxEstado.removeAllItems();
        for (var x : estados) {
            ComboBoxEstado.addItem(x);
        }
        
        ElegirDistribucion();
    }

    private void ElegirDistribucion(){
        
        if(ComboBoxDistribucion.getSelectedIndex() ==0){
            SpinnerDia.setEnabled(false);
            SpinnerMes.setEnabled(false);
            SpinnerAno.setEnabled(false);
            
            ComboBoxEstado.setEnabled(false);
            ButtonConfirmar.setEnabled(false);
            
        }
        else{
            SpinnerDia.setEnabled(true);
            SpinnerMes.setEnabled(true);
            SpinnerAno.setEnabled(true);
            
            ComboBoxEstado.setEnabled(true);
            ButtonConfirmar.setEnabled(true);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ComboBoxDistribucion = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ComboBoxEstado = new javax.swing.JComboBox<>();
        SpinnerDia = new javax.swing.JSpinner();
        SpinnerMes = new javax.swing.JSpinner();
        SpinnerAno = new javax.swing.JSpinner();
        ButtonConfirmar = new javax.swing.JButton();
        ButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleccione la distribucion a Modificar");

        ComboBoxDistribucion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxDistribucion.setPreferredSize(new java.awt.Dimension(328, 23));
        ComboBoxDistribucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxDistribucionActionPerformed(evt);
            }
        });

        jLabel2.setText("Nueva Fecha:");

        jLabel3.setText("Nuevo Estado:");

        ComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxEstado.setMinimumSize(new java.awt.Dimension(110, 23));

        SpinnerDia.setPreferredSize(new java.awt.Dimension(55, 23));

        SpinnerMes.setPreferredSize(new java.awt.Dimension(55, 23));

        SpinnerAno.setPreferredSize(new java.awt.Dimension(87, 23));

        ButtonConfirmar.setText("Confirmar");
        ButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConfirmarActionPerformed(evt);
            }
        });

        ButtonCancelar.setText("Cancelar");
        ButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ComboBoxDistribucion, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(27, 27, 27)
                                .addComponent(SpinnerDia, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SpinnerMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SpinnerAno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(ButtonConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonCancelar)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(ComboBoxDistribucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(SpinnerDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpinnerMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpinnerAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonConfirmar)
                    .addComponent(ButtonCancelar))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConfirmarActionPerformed
        if(ComboBoxDistribucion.getSelectedIndex() ==0) return;
        
        String mensaje = "Ingrese un numero";
        
        try {
            int dia = (Integer)(SpinnerDia.getValue());
            int mes = (Integer)(SpinnerMes.getValue());
            int ano = (Integer)(SpinnerAno.getValue());            

            System.out.println("Fecha ingresada: " + dia + "/" + mes + "/" + ano);

            if(dia < 1 || dia > 31){
                mensaje = "Día inválido";
                throw new Exception();
            }
            if(mes < 1 || mes > 12){
                mensaje = "Mes inválido";
                throw new Exception();
            }

            if((mes == 4 || mes == 6 || mes == 9 || mes == 11) && dia > 30){
                mensaje = "Día inválido";
                throw new Exception();
            }

            if(mes == 2) {
                if(dia > 29) {
                    mensaje = "Día inválido";
                    throw new Exception();
                }
                if(dia == 29 && !(ano % 4 == 0 && (ano % 100 != 0 || ano % 400 == 0))) {
                    mensaje = "Día inválido en año no bisiesto";
                    throw new Exception();
                }
            }
            
            FabricaCDistribucion.getControlador().ModificarDatosDistribucion( 
                    distribuciones.get(ComboBoxDistribucion.getSelectedIndex()-1),
                    LocalDate.of(ano,mes,dia), EstadoDistribucion.ENTREGADO);
            
            // Mensaje de éxito
            JOptionPane.showMessageDialog(null, 
            "Distribucion Editada exitosamente", 
            "Éxito", 
            JOptionPane.INFORMATION_MESSAGE);
            
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, 
            mensaje, 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_ButtonConfirmarActionPerformed

    private void ButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_ButtonCancelarActionPerformed

    private void ComboBoxDistribucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxDistribucionActionPerformed
        ElegirDistribucion();

    }//GEN-LAST:event_ComboBoxDistribucionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarDistribucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarDistribucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarDistribucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarDistribucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarDistribucion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JButton ButtonConfirmar;
    private javax.swing.JComboBox<String> ComboBoxDistribucion;
    private javax.swing.JComboBox<String> ComboBoxEstado;
    private javax.swing.JSpinner SpinnerAno;
    private javax.swing.JSpinner SpinnerDia;
    private javax.swing.JSpinner SpinnerMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
